### ISSUE TITLE
Arbitrary key:value Opaque secrets not synced

### ISSUE THREAD

**Issue by megakoresh** [openshift/jenkins-sync-plugin#255]
If I define a secret like this:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: secret1
  labels:
    credential.sync.jenkins.openshift.io: 'true'
stringData:
  npmrc__auth: myamazingtokeneggsdedededede
  secret_fetish: too_weird_to_show
```

Then jenkins sync plugin will ignore it because it doesn't recognize any of it's usual patterns such as username/password or token and somesuch. It would be useful for these secrets to be still synced as Secret text type, especially if they are synced in Json format. Then pipeline script can parse the json into an object.
