### ISSUE TITLE
RFE: YAML PodTemplate support for Agent ConfigMap's

### ISSUE THREAD

**Issue by brix4dayz** [openshift/jenkins-sync-plugin#257]
The Kubernetes plugin not too recently added a feature for providing your own YAML for Agent PodTemplate's instead: https://github.com/jenkinsci/kubernetes-plugin/pull/275.

I was imagining the sync plugin could start supporting this through an additional label on the ConfigMap's, maybe `fileType` whose values would be either `XML`, `YAML`, `yml`, `yaml`, or `xml`. Then `ConfigMapWatcher.podTemplatesFromConfigMap` could either build the class from XML, or use kubernetes' plugins `PodTemplateBuilder` to build from the YAML.

@gabemontero I saw you helped with the UI  for that feature https://github.com/jenkinsci/kubernetes-plugin/pull/311. Is there any reason why this might not be viable for the sync plugin? I didn't see anything on the Trello board for this yet.

I might give it a shot myself, but was wondering if theres anything I need to be aware of. Thanks!

**Comment by bparees** [comment]
You can already define an entire slave pod template in a configmap that the sync plugin will turn into a slave pod definition:  https://docs.okd.io/latest/using_images/other_images/jenkins.html#configuring-the-jenkins-kubernetes-plug-in

Does that not cover this?

**Comment by brix4dayz** [comment]
This would be an enhancement for that, right now that only supports the serialized XML. The kubernetes-plugin PR I linked to allows you define the agent in a YAML pod template which would be preferable since the XML doesn't support things like `valueFrom.fieldRef/resourceFieldRef` for instance.

We could also just define agents dynamically in the pipeline itself like the docs you linked describe further down, but this is problematic because you _should_ create a unique label for the dynamic agents every build which renders the `instanceCap` useless from what I've seen. Unless I'm missing something there.

**Comment by bparees** [comment]
@brix4dayz I would assume you could simply define your xml as roughly:

 <org.csanchez.jenkins.plugins.kubernetes.PodTemplate>
      <name>template1</name>
      <yaml>your inline yaml goes here</yaml>
    </org.csanchez.jenkins.plugins.kubernetes.PodTemplate>

is that not the case?

**Comment by bparees** [comment]
ok, well that's how i'd expect us to handle this, there may be some formatting issues we need to sort out or something in the sync plugin's processing of the configmap content though.

**Comment by brix4dayz** [comment]
Got it, thanks! Lemme know if I can test anything else out or if I need reformat it somehow. 

But I mean wouldn't the whole thing get a little easier (and easier to read) if we took the XML "middle man" out? Thats where it seems like the Kubernetes plugin itself is heading. The fields of `PodTemplate` that aren't apart of the K8s API (i.e. `instanceCap`, "agent" `label`) could just be keys in the configmap.

So maybe something like this:
```
- kind: ConfigMap
  apiVersion: v1
  metadata:
    labels:
      role: jenkins-slave
    name: bw-maven
  data:
    instanceCap: 5
    label: bw-maven
    yaml: |-
          kind: Pod
          apiVersion: v1
          metadata:
            labels:
              custom-label: "thing"
          spec:
            serviceAccountName: jenkins
            containers:
              - name: jnlp
                image: openshift/jenkins-slave-maven-centos7
                workingDir: /home/jenkins
                tty: false
                args:
                  - ${computer.jnlpmac}
                  - ${computer.name}
                resources:
                  requests:
                    cpu: ${AGENT_CPU_REQUEST}
                    memory: ${AGENT_MEM_REQUEST}
                  limits:
                    cpu: ${AGENT_CPU_LIMIT}
                    memory: ${AGENT_MEM_LIMIT}
                env:
                  - name: GIT_SOURCE_URL
                    value: ${GIT_SOURCE_URL}
                  - name: CLUSTER_APPS_DOMAIN
                    value: ${CLUSTER_APPS_DOMAIN}
                  - name: CLUSTER_LOCATION
                    value: ${CLUSTER_LOCATION}
                  - name: JENKINS_NAMESPACE
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.namespace
                volumeMounts:
                  - mountPath: /home/jenkins/.m2
                    name: jenkins-m2-settings
                  - mountPath: /home/jenkins/.m2-repository
                    name: bw-agent-cache-pvc
            volumes:
              - name: jenkins-m2-settings
                secret:
                  secretName: jenkins-m2-settings
              - name: bw-agent-cache-pvc
                persistentVolumeClaim:
                  claimName: bw-agent-cache-pvc
```
