### ISSUE TITLE
Injection of ssh private key into jenkins needs manual update to work

### ISSUE THREAD

**Issue by extern-stamp-julian** [openshift/jenkins-sync-plugin#345]
Hi,

I am configuring a permanent ssh agent and for that purpose I want to inject the private ssh key from an openshift secret.
The yaml-file of my secret looks like this:

```
apiVersion: v1
data:
  ssh-privatekey: ${key_base64}
  username: ${username_base64}
kind: Secret
metadata:
  labels:
    credential.sync.jenkins.openshift.io: 'true'
  name: ssh-agent
  namespace: project
type: kubernetes.io/ssh-auth

```

The injection works fine.

When I deploy the jenkins pod, the ssh agent does not manage to start. The error message is:

```
[09/30/19 08:48:54] [SSH] Opening SSH connection to ${server-adress}:22.
[09/30/19 08:48:56] [SSH] SSH host key matches key seen previously for this host. Connection will be allowed.
ERROR: Server rejected the 1 private key(s) for jenkins
 (credentialId:project-ssh-agent/method:publickey)
[09/30/19 08:48:56] [SSH] Authentication failed.
Authentication failed.
[09/30/19 08:48:56] Launch failed - cleaning up connection
[09/30/19 08:48:56] [SSH] Connection closed.
```

In order to get the connection working, I go to the credentials store in the Jenkins UI `https://${jenkins-url}/credentials/store/system/domain/_/credential/project-ssh-agent/update`, , go to `Update` credentials and click on `Save` without having changed anything about the credentials. 

Clicking on `relaunch agent` now spawns the agent using the ssh connection to connect to the remote server as configured. 

I tried several things in Openshift when creating the secret: 
- import the ssh private key from a file that was processed with `dos2unix` and vice versa `unix2dos`
- for both cases above, have the file end with an empty new line and without
- encode the key using the command line base64 tool and copy-paste the result into the `Edit yaml` editor interactively in openshift. Here, not all cases that I described above worked, Openshift would reject the strings that were generated from the `dos` formated files with `Failed to process the resource.`

Can you tell me what exactly I have to do to have the injection result in credentials that enable my jenkins to authenticate with the ssh agent? Is this something that could be made more reliable?
