### ISSUE TITLE
Jenkins 2.190.2 Git source secret not configured on jenkins pipeline

### ISSUE THREAD

**Issue by rayanebel** [openshift/jenkins-sync-plugin#359]
Hello,

Currently I have a Jenkins instance running on Openshift with the `jenkins-sync-plugin` installed and configured. After that I tried to create my first pipeline using `BuildConfig` object that will fetch a `Jenkinsfile` in a remote private github repository (HTTPS). So to access to this private repository I have created a `basic-auth` secret and I include the reference to this secret in my buildconfig.

```
    sourceSecret:
      name: "basicsecret"
```
When I apply my buildconfig, I have my pipeline which was created on my jenkins instance but, when I look at the details of this pipeline, Openshift didn't put my `git` credentials and let the value to `None` while I have the secret synchronized in Jenkins. So as a result when I launch my pipeline I have an error that said : 

```
OpenShift Build eb-cicd-eu-dev-axa-ebp-fr/samdoctor-pipeline-example-2-3 from https://github.com/thedigitalstudio/samquote-api-tests.git
Checking out git https://github.com/thedigitalstudio/samquote-api-tests.git into /var/jenkins_home/workspace/eb-cicd-eu-dev-axa-ebp-fr/eb-cicd-eu-dev-axa-ebp-fr-samdoctor-pipeline-example-2@script to read Jenkinsfile
No credentials specified
```
I also tried to manually change `None` value to point to my `secret` but when I launch again my pipeline from Openshift, my job is reconfigured and I have again no git credentials (None value)

Can you help to understand why my `git` credential is not configured in my Jenkins pipeline ?

**Additional informations**

- Jenkins version: `2.190.2`
- Openshift sync plugin: `1.0.42`
- Openshift version: 3.10
- Buildconfig: 

```
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: samdoctor-pipeline-example-2
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      httpProxy: http://proxy-build-ext:8080
      httpsProxy: http://proxy-build-ext:8080
      ref: rbe-tests
      uri: https://github.com/xxxxxxxx/xxxxxxx.git
    sourceSecret:
      name: "basicsecret"
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
  successfulBuildsHistoryLimit: 5
  triggers: []
```

- Result when pipeline is dynamically created on jenkins (credential is set to none)

<img width="1280" alt="Capture d’écran 2019-11-05 à 17 55 39" src="https://user-images.githubusercontent.com/15887095/68228405-aada1480-fff5-11e9-9b77-b1e29b0e7767.png">

Thanks.
