### ISSUE TITLE
Branch name (refSpec) in Job is not reflected to BuildConfig

### ISSUE THREAD

**Issue by rayanebel** [openshift/jenkins-sync-plugin#362]
Hello,

Currently I have a Jenkins instance running on Openshift with the jenkins-sync-plugin installed and configured.

I have a `Jenkinfile` into a git repository in a specific branch called `rbe-tests` and I have created the following buildconfig to automatically create my pipeline configuration into my Jenkins instance:

```
apiVersion: "v1"
kind: "BuildConfig"
metadata:
  name: "samdoctor-pipeline-example"
spec:
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "768Mi"
  source:
    git:
      uri: "https://github.com/thedigitalstudio/samquote-api-tests"
      httpProxy: http://proxy-build-ext:8080
      httpsProxy: http://proxy-build-ext:8080
      ref: "rbe-tests"
    sourceSecret:
      name: "jenkins-git-credentials"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
```

As a result I have the following configuration on jenkins :

<img width="1280" alt="capture-1" src="https://user-images.githubusercontent.com/15887095/69330885-1e199280-0c54-11ea-906e-c48ea47c9c59.png">

When I run a build directly from `Openshift` or `Jenkins`, Jenkins will fetch the Jenkinsfile and execute my pipeline successfully. Now, If I make a changes into my Jenkinsfile and re-run a new build, Jenkins still use the old version of my Jenkinsfile. The only workaround is to connect to the Jenkins master container and delete manually the workspace that is not really good. I have also check the `Additional behaviors` from `git-plugin` but Openshift is not able to configure this option from the buildconfig object and I can't set it manually because Openshift will reset and re-synchronize the configuration.

After that, I duplicate my pipeline into Jenkins and when I remove the `refspec` into the advanced SCM configuration then, set a blank value and run a new build, Jenkins is able to fetch new commit on my Jenkinsfile.

<img width="1280" alt="capture-2" src="https://user-images.githubusercontent.com/15887095/69330903-240f7380-0c54-11ea-876d-3678f8bcfb6b.png">

Can you help to understand why Jenkins is not able to fetch my latest Jenkinsfile ?

**Additional informations**

Jenkins version: 2.190.2
Openshift sync plugin: 1.0.43
Openshift version: 3.10

Thanks you.
